// Kenya counties, constituencies and wards - IEBC official delimitation
const KENYA_LOCATIONS = [
  { code:'001', name:'Mombasa', constituencies:[
    { code:'001', name:'Changamwe', wards:[{code:'001',name:'Port Reitz'},{code:'002',name:'Kipevu'},{code:'003',name:'Airport'},{code:'004',name:'Changamwe'},{code:'005',name:'Chaani'}] },
    { code:'002', name:'Jomvu', wards:[{code:'001',name:'Jomvu Kuu'},{code:'002',name:'Magogoni'},{code:'003',name:'Mikindani'}] },
    { code:'003', name:'Kisauni', wards:[{code:'001',name:'Mjambere'},{code:'002',name:'Junda'},{code:'003',name:'Bamburi'},{code:'004',name:'Mwakirunge'},{code:'005',name:'Mtopanga'},{code:'006',name:'Magogoni'},{code:'007',name:'Shanzu'}] },
    { code:'004', name:'Nyali', wards:[{code:'001',name:'Frere Town'},{code:'002',name:'Ziwa La Ng\'ombe'},{code:'003',name:'Mkomani'},{code:'004',name:'Kongowea'},{code:'005',name:'Kadzandani'}] },
    { code:'005', name:'Likoni', wards:[{code:'001',name:'Mtongwe'},{code:'002',name:'Shika Adabu'},{code:'003',name:'Bofu'},{code:'004',name:'Likoni'},{code:'005',name:'Timbwani'}] },
    { code:'006', name:'Mvita', wards:[{code:'001',name:'Mji Wa Kale/Makadara'},{code:'002',name:'Tudor'},{code:'003',name:'Tononoka'},{code:'004',name:'Shimanzi/Ganjoni'},{code:'005',name:'Majengo'}] },
  ]},
  { code:'002', name:'Kwale', constituencies:[
    { code:'001', name:'Msambweni', wards:[{code:'001',name:'Gombato Bongwe'},{code:'002',name:'Ukunda'},{code:'003',name:'Kinondo'},{code:'004',name:'Ramisi'}] },
    { code:'002', name:'Lunga Lunga', wards:[{code:'001',name:'Pongwe/Kikoneni'},{code:'002',name:'Dzombo'},{code:'003',name:'Mwereni'},{code:'004',name:'Vanga'}] },
    { code:'003', name:'Matuga', wards:[{code:'001',name:'Tsimba Golini'},{code:'002',name:'Waa'},{code:'003',name:'Tiwi'},{code:'004',name:'Kubo South'},{code:'005',name:'Mackinnon Road'}] },
    { code:'004', name:'Kinango', wards:[{code:'001',name:'Ndavaya'},{code:'002',name:'Puma'},{code:'003',name:'Kinango'},{code:'004',name:'Mackinnon Road'},{code:'005',name:'Chengoni/Samburu'},{code:'006',name:'Mwavumbo'},{code:'007',name:'Kasemeni'}] },
  ]},
  { code:'003', name:'Kilifi', constituencies:[
    { code:'001', name:'Kilifi North', wards:[{code:'001',name:'Tezo'},{code:'002',name:'Sokoni'},{code:'003',name:'Kibarani'},{code:'004',name:'Dabaso'},{code:'005',name:'Matsangoni'},{code:'006',name:'Watamu'},{code:'007',name:'Mnarani'}] },
    { code:'002', name:'Kilifi South', wards:[{code:'001',name:'Junju'},{code:'002',name:'Mwarakaya'},{code:'003',name:'Shimo La Tewa'},{code:'004',name:'Chasimba'},{code:'005',name:'Mtepeni'}] },
    { code:'003', name:'Kaloleni', wards:[{code:'001',name:'Mariakani'},{code:'002',name:'Kayafungo'},{code:'003',name:'Urban'},{code:'004',name:'Mwanamwinga'}] },
    { code:'004', name:'Rabai', wards:[{code:'001',name:'Mwawesa'},{code:'002',name:'Ruruma'},{code:'003',name:'Kambe/Ribe'},{code:'004',name:'Rabai/Samburu'}] },
    { code:'005', name:'Ganze', wards:[{code:'001',name:'Ganze'},{code:'002',name:'Bamba'},{code:'003',name:'Jaribuni'},{code:'004',name:'Sokoke'}] },
    { code:'006', name:'Malindi', wards:[{code:'001',name:'Jilore'},{code:'002',name:'Kakuyuni'},{code:'003',name:'Ganda'},{code:'004',name:'Malindi Town'},{code:'005',name:'Shella'}] },
    { code:'007', name:'Magarini', wards:[{code:'001',name:'Adu'},{code:'002',name:'Gongoni'},{code:'003',name:'Marafa'},{code:'004',name:'Magarini'},{code:'005',name:'Garashi'},{code:'006',name:'Imalkazana'}] },
  ]},
  { code:'004', name:'Tana River', constituencies:[
    { code:'001', name:'Garsen', wards:[{code:'001',name:'Kipini East'},{code:'002',name:'Garsen South'},{code:'003',name:'Kipini West'},{code:'004',name:'Garsen West'},{code:'005',name:'Garsen North'},{code:'006',name:'Garsen Central'}] },
    { code:'002', name:'Galole', wards:[{code:'001',name:'Wayu'},{code:'002',name:'Chewele'},{code:'003',name:'Hirimani'},{code:'004',name:'Mikinduni'},{code:'005',name:'Shauri Moyo'}] },
    { code:'003', name:'Bura', wards:[{code:'001',name:'Chewele'},{code:'002',name:'Wayu'},{code:'003',name:'Bangale'},{code:'004',name:'Sala'},{code:'005',name:'Madogo'}] },
  ]},
  { code:'005', name:'Lamu', constituencies:[
    { code:'001', name:'Lamu East', wards:[{code:'001',name:'Faza'},{code:'002',name:'Kiunga'},{code:'003',name:'Basuba'}] },
    { code:'002', name:'Lamu West', wards:[{code:'001',name:'Shela'},{code:'002',name:'Mkomani'},{code:'003',name:'Hindi'},{code:'004',name:'Mkunumbi'},{code:'005',name:'Hongwe'},{code:'006',name:'Witu'},{code:'007',name:'Bahari'}] },
  ]},
  { code:'006', name:'Taita Taveta', constituencies:[
    { code:'001', name:'Taveta', wards:[{code:'001',name:'Chala'},{code:'002',name:'Mahoo'},{code:'003',name:'Bomani'},{code:'004',name:'Mboghoni'},{code:'005',name:'Mata'}] },
    { code:'002', name:'Wundanyi', wards:[{code:'001',name:'Wundanyi/Mbale'},{code:'002',name:'Werugha'},{code:'003',name:'Wumingu/Kishushe'},{code:'004',name:'Mwanda/Mgange'}] },
    { code:'003', name:'Mwatate', wards:[{code:'001',name:'Ronge'},{code:'002',name:'Mwatate'},{code:'003',name:'Bura'},{code:'004',name:'Chawia'},{code:'005',name:'Wusi/Kishamba'}] },
    { code:'004', name:'Voi', wards:[{code:'001',name:'Mbololo'},{code:'002',name:'Sagala'},{code:'003',name:'Kaloleni'},{code:'004',name:'Marungu'},{code:'005',name:'Ilore'},{code:'006',name:'Ngolia'}] },
  ]},
  { code:'007', name:'Garissa', constituencies:[
    { code:'001', name:'Garissa Township', wards:[{code:'001',name:'Township'},{code:'002',name:'Waberi'},{code:'003',name:'Galbet'},{code:'004',name:'Iftin'}] },
    { code:'002', name:'Balambala', wards:[{code:'001',name:'Balambala'},{code:'002',name:'Danyere'},{code:'003',name:'Jarajara'},{code:'004',name:'Saka'},{code:'005',name:'Sankuri'}] },
    { code:'003', name:'Lagdera', wards:[{code:'001',name:'Modogashe'},{code:'002',name:'Benane'},{code:'003',name:'Goreale'},{code:'004',name:'Maalimin'},{code:'005',name:'Sabena'},{code:'006',name:'Baraki'}] },
    { code:'004', name:'Dadaab', wards:[{code:'001',name:'Dertu'},{code:'002',name:'Dadaab'},{code:'003',name:'Labasigale'},{code:'004',name:'Damajale'},{code:'005',name:'Liboi'},{code:'006',name:'Abakaile'}] },
    { code:'005', name:'Fafi', wards:[{code:'001',name:'Bura'},{code:'002',name:'Dekaharia'},{code:'003',name:'Jarajara'},{code:'004',name:'Kotile'},{code:'005',name:'Nanighi'}] },
    { code:'006', name:'Ijara', wards:[{code:'001',name:'Ijara'},{code:'002',name:'Masalani'},{code:'003',name:'Fino'},{code:'004',name:'Hulugho'},{code:'005',name:'Sangailu'},{code:'006',name:'Garsen'}] },
  ]},
  { code:'008', name:'Wajir', constituencies:[
    { code:'001', name:'Wajir North', wards:[{code:'001',name:'Gurar'},{code:'002',name:'Bute'},{code:'003',name:'Griftu'},{code:'004',name:'Wajir Bor'},{code:'005',name:'Tarbaj'}] },
    { code:'002', name:'Wajir East', wards:[{code:'001',name:'Wajir East'},{code:'002',name:'Barwaqo'},{code:'003',name:'Korondile'},{code:'004',name:'Hadado/Athibohol'}] },
    { code:'003', name:'Tarbaj', wards:[{code:'001',name:'Tarbaj'},{code:'002',name:'Wargadud'},{code:'003',name:'Kutulo'},{code:'004',name:'Elwak North'}] },
    { code:'004', name:'Wajir West', wards:[{code:'001',name:'Eldas'},{code:'002',name:'Lafey'},{code:'003',name:'Ademasajide'}] },
    { code:'005', name:'Eldas', wards:[{code:'001',name:'Eldas'},{code:'002',name:'Dambas'},{code:'003',name:'Chombo'},{code:'004',name:'Arbajahan'}] },
    { code:'006', name:'Wajir South', wards:[{code:'001',name:'Benane'},{code:'002',name:'Habaswein'},{code:'003',name:'Lagboghol North'},{code:'004',name:'Matarba'},{code:'005',name:'Lagboghol South'}] },
  ]},
  { code:'009', name:'Mandera', constituencies:[
    { code:'001', name:'Mandera West', wards:[{code:'001',name:'Takaba South'},{code:'002',name:'Takaba'},{code:'003',name:'Lagsure'},{code:'004',name:'Dandu'},{code:'005',name:'Khalalio'}] },
    { code:'002', name:'Banissa', wards:[{code:'001',name:'Banissa'},{code:'002',name:'Derkhale'},{code:'003',name:'Gari'},{code:'004',name:'Malkamari'}] },
    { code:'003', name:'Mandera North', wards:[{code:'001',name:'Ashabito'},{code:'002',name:'Guticha'},{code:'003',name:'Mororo'},{code:'004',name:'Rhamu'},{code:'005',name:'Rhamu Dimtu'}] },
    { code:'004', name:'Mandera South', wards:[{code:'001',name:'Wargadud'},{code:'002',name:'Kutulo'},{code:'003',name:'Elwak North'},{code:'004',name:'Elwak South'}] },
    { code:'005', name:'Mandera East', wards:[{code:'001',name:'Arabia'},{code:'002',name:'Bulla Mpya'},{code:'003',name:'Khalalio'},{code:'004',name:'Neboi'}] },
    { code:'006', name:'Lafey', wards:[{code:'001',name:'Lafey'},{code:'002',name:'Fino'},{code:'003',name:'Lafey North'},{code:'004',name:'Sankuri'}] },
  ]},
  { code:'010', name:'Marsabit', constituencies:[
    { code:'001', name:'Moyale', wards:[{code:'001',name:'Moyale Township'},{code:'002',name:'Butiye'},{code:'003',name:'Sololo'},{code:'004',name:'Heillu/Manyatta'}] },
    { code:'002', name:'North Horr', wards:[{code:'001',name:'Dukana'},{code:'002',name:'Maikona'},{code:'003',name:'North Horr'},{code:'004',name:'Kalacha'}] },
    { code:'003', name:'Saku', wards:[{code:'001',name:'Sagante/Jaldesa'},{code:'002',name:'Karare'},{code:'003',name:'Marsabit Central'}] },
    { code:'004', name:'Laisamis', wards:[{code:'001',name:'Laisamis'},{code:'002',name:'Logologo'},{code:'003',name:'Korr/Ngurunit'},{code:'004',name:'Loiyangalani'},{code:'005',name:'Kargi/South Horr'}] },
  ]},
  { code:'011', name:'Isiolo', constituencies:[
    { code:'001', name:'Isiolo North', wards:[{code:'001',name:'Wabera'},{code:'002',name:'Bulla Pesa'},{code:'003',name:'Ngare Mara'},{code:'004',name:'Oldonyiro'},{code:'005',name:'Chari'}] },
    { code:'002', name:'Isiolo South', wards:[{code:'001',name:'Garbatulla'},{code:'002',name:'Kina'},{code:'003',name:'Sericho'}] },
  ]},
  { code:'012', name:'Meru', constituencies:[
    { code:'001', name:'Igembe South', wards:[{code:'001',name:'Maua'},{code:'002',name:'Kiegoi/Antubochiu'},{code:'003',name:'Akachiu'},{code:'004',name:'Kanuni'}] },
    { code:'002', name:'Igembe Central', wards:[{code:'001',name:'Njia'},{code:'002',name:'Kangeta'},{code:'003',name:'Igembe'}] },
    { code:'003', name:'Igembe North', wards:[{code:'001',name:'Antubochio'},{code:'002',name:'Ntunene'},{code:'003',name:'Amwathi'}] },
    { code:'004', name:'Tigania West', wards:[{code:'001',name:'Mikinduri'},{code:'002',name:'Karama'},{code:'003',name:'Nkomo'},{code:'004',name:'Mbeu'},{code:'005',name:'Athwana'}] },
    { code:'005', name:'Tigania East', wards:[{code:'001',name:'Nthangacha'},{code:'002',name:'Old Nthi'},{code:'003',name:'Karama'},{code:'004',name:'Kiguchwa'}] },
    { code:'006', name:'North Imenti', wards:[{code:'001',name:'Municipality'},{code:'002',name:'Ntima East'},{code:'003',name:'Ntima West'},{code:'004',name:'Nyaki West'},{code:'005',name:'Nyaki East'}] },
    { code:'007', name:'Buuri', wards:[{code:'001',name:'Timau'},{code:'002',name:'Kisima'},{code:'003',name:'Ruiri/Rwarera'},{code:'004',name:'Kiirua/Naari'}] },
    { code:'008', name:'Central Imenti', wards:[{code:'001',name:'Mwanganthia'},{code:'002',name:'Abothuguchi Central'},{code:'003',name:'Abothuguchi West'},{code:'004',name:'Kiagu'}] },
    { code:'009', name:'South Imenti', wards:[{code:'001',name:'Mitunguu'},{code:'002',name:'Igoji East'},{code:'003',name:'Igoji West'},{code:'004',name:'Akimba'},{code:'005',name:'Mwimbi'}] },
  ]},
  { code:'013', name:'Tharaka Nithi', constituencies:[
    { code:'001', name:'Maara', wards:[{code:'001',name:'Kibung\'a'},{code:'002',name:'Ntoroni'},{code:'003',name:'Mwimbi'},{code:'004',name:'Ganga'},{code:'005',name:'Chogoria'}] },
    { code:'002', name:'Chuka/Igambang\'ombe', wards:[{code:'001',name:'Karingani'},{code:'002',name:'Mugwe'},{code:'003',name:'Igambang\'ombe'},{code:'004',name:'Mariani'}] },
    { code:'003', name:'Tharaka', wards:[{code:'001',name:'Gatunga'},{code:'002',name:'Mukothima'},{code:'003',name:'Nkondi'},{code:'004',name:'Tharaka'}] },
  ]},
  { code:'014', name:'Embu', constituencies:[
    { code:'001', name:'Manyatta', wards:[{code:'001',name:'Ruguru'},{code:'002',name:'Nginda'},{code:'003',name:'Mbeti North'},{code:'004',name:'Kirimari'},{code:'005',name:'Gaturi South'}] },
    { code:'002', name:'Runyenjes', wards:[{code:'001',name:'Gaturi North'},{code:'002',name:'Kagaari South'},{code:'003',name:'Central'},{code:'004',name:'Kagaari North'},{code:'005',name:'Kyeni North'},{code:'006',name:'Kyeni South'}] },
    { code:'003', name:'Mbeere South', wards:[{code:'001',name:'Mwea'},{code:'002',name:'Makima'},{code:'003',name:'Mbeti South'},{code:'004',name:'Mavuria'},{code:'005',name:'Kiambere'}] },
    { code:'004', name:'Mbeere North', wards:[{code:'001',name:'Nthawa'},{code:'002',name:'Nthangu'},{code:'003',name:'Evurore'}] },
  ]},
  { code:'015', name:'Kitui', constituencies:[
    { code:'001', name:'Mwingi North', wards:[{code:'001',name:'Kyuso'},{code:'002',name:'Mumoni'},{code:'003',name:'Tseikuru'},{code:'004',name:'Tharaka'}] },
    { code:'002', name:'Mwingi West', wards:[{code:'001',name:'Kyome/Thaana'},{code:'002',name:'Nguutani'},{code:'003',name:'Migwani'},{code:'004',name:'Kiomo/Kyethani'}] },
    { code:'003', name:'Mwingi Central', wards:[{code:'001',name:'Central'},{code:'002',name:'Kivou'},{code:'003',name:'Nguni'},{code:'004',name:'Nuu'},{code:'005',name:'Mui'}] },
    { code:'004', name:'Kitui West', wards:[{code:'001',name:'Mutonguni'},{code:'002',name:'Kauwi'},{code:'003',name:'Matinyani'},{code:'004',name:'Kwa Mutonga/Kithumula'}] },
    { code:'005', name:'Kitui Rural', wards:[{code:'001',name:'Kisasi'},{code:'002',name:'Mwitika'},{code:'003',name:'Mutitu/Kaliku'},{code:'004',name:'Nzambani'},{code:'005',name:'Ikanga/Kyatune'}] },
    { code:'006', name:'Kitui Central', wards:[{code:'001',name:'Miambani'},{code:'002',name:'Township'},{code:'003',name:'Kyangwithya West'},{code:'004',name:'Mulango'},{code:'005',name:'Kyangwithya East'}] },
    { code:'007', name:'Kitui East', wards:[{code:'001',name:'Zombe/Mwitika'},{code:'002',name:'Shambani'},{code:'003',name:'Mutito/Kaliku'},{code:'004',name:'Endau/Malalani'}] },
    { code:'008', name:'Kitui South', wards:[{code:'001',name:'Ikutha'},{code:'002',name:'Athi'},{code:'003',name:'Mutha'},{code:'004',name:'Kanziko'},{code:'005',name:'Ngomeni'}] },
  ]},
  { code:'016', name:'Machakos', constituencies:[
    { code:'001', name:'Masinga', wards:[{code:'001',name:'Masinga Central'},{code:'002',name:'Ekalakala'},{code:'003',name:'Miwani'},{code:'004',name:'Kivaa'},{code:'005',name:'Mbee'}] },
    { code:'002', name:'Yatta', wards:[{code:'001',name:'Ndalani'},{code:'002',name:'Matuu'},{code:'003',name:'Kithimba'},{code:'004',name:'Central'},{code:'005',name:'Ikombe'},{code:'006',name:'Katangi'}] },
    { code:'003', name:'Kangundo', wards:[{code:'001',name:'Kangundo North'},{code:'002',name:'Kangundo Central'},{code:'003',name:'Kangundo East'},{code:'004',name:'Kangundo West'}] },
    { code:'004', name:'Matungulu', wards:[{code:'001',name:'Tala'},{code:'002',name:'Matungulu North'},{code:'003',name:'Matungulu East'},{code:'004',name:'Matungulu West'},{code:'005',name:'Kyeleni'}] },
    { code:'005', name:'Kathiani', wards:[{code:'001',name:'Mitaboni'},{code:'002',name:'Kathiani Central'},{code:'003',name:'Upper Kaewa/Iveti'},{code:'004',name:'Lower Kaewa'}] },
    { code:'006', name:'Mavoko', wards:[{code:'001',name:'Athi River'},{code:'002',name:'Kinanie'},{code:'003',name:'Muthwani'},{code:'004',name:'Syokimau/Mulolongo'}] },
    { code:'007', name:'Machakos Town', wards:[{code:'001',name:'Machakos Central'},{code:'002',name:'Mua'},{code:'003',name:'Mutituni'},{code:'004',name:'Kalama'},{code:'005',name:'Muvuti/Kisukari'}] },
    { code:'008', name:'Mwala', wards:[{code:'001',name:'Mbiuni'},{code:'002',name:'Makutano/Mwala'},{code:'003',name:'Mwala'},{code:'004',name:'Kibauni'},{code:'005',name:'Wamunyu'}] },
  ]},
  { code:'017', name:'Makueni', constituencies:[
    { code:'001', name:'Mbooni', wards:[{code:'001',name:'Tulimani'},{code:'002',name:'Mbooni'},{code:'003',name:'Kithungo/Kitundu'},{code:'004',name:'Kisau/Kiteta'}] },
    { code:'002', name:'Kilome', wards:[{code:'001',name:'Masongaleni'},{code:'002',name:'Tulimani'},{code:'003',name:'Mukaa'},{code:'004',name:'Kiima Kiu/Kalanzoni'}] },
    { code:'003', name:'Kaiti', wards:[{code:'001',name:'Ukia'},{code:'002',name:'Kee'},{code:'003',name:'Kilungu'},{code:'004',name:'Ilima'}] },
    { code:'004', name:'Makueni', wards:[{code:'001',name:'Wote'},{code:'002',name:'Muvau/Kikumini'},{code:'003',name:'Mavindini'},{code:'004',name:'Nguu/Masumba'},{code:'005',name:'Kathonzweni'}] },
    { code:'005', name:'Kibwezi West', wards:[{code:'001',name:'Makindu'},{code:'002',name:'Nguumo'},{code:'003',name:'Kikumbulyu North'},{code:'004',name:'Kikumbulyu South'},{code:'005',name:'Ngai/Ndethya'}] },
    { code:'006', name:'Kibwezi East', wards:[{code:'001',name:'Masongaleni'},{code:'002',name:'Mtito Andei'},{code:'003',name:'Thange'},{code:'004',name:'Ivingoni/Nzambani'}] },
  ]},
  { code:'018', name:'Nyandarua', constituencies:[
    { code:'001', name:'Kinangop', wards:[{code:'001',name:'Engineer'},{code:'002',name:'Gathara'},{code:'003',name:'North Kinangop'},{code:'004',name:'Murungaru'},{code:'005',name:'Njabini/Kiburu'},{code:'006',name:'Nyakio'}] },
    { code:'002', name:'Kipipiri', wards:[{code:'001',name:'Geta'},{code:'002',name:'Githioro'},{code:'003',name:'Karau'},{code:'004',name:'Kipipiri'},{code:'005',name:'Wanjohi'},{code:'006',name:'King\'ang\'i/Gacharage'}] },
    { code:'003', name:'Ol Kalou', wards:[{code:'001',name:'Gathanji'},{code:'002',name:'Kanjuiri'},{code:'003',name:'Mirangine'},{code:'004',name:'Kahuro'},{code:'005',name:'Ol Kalou'},{code:'006',name:'Rurii'}] },
    { code:'004', name:'Ol Jorok', wards:[{code:'001',name:'Charagita'},{code:'002',name:'Leshau'},{code:'003',name:'Pondo'},{code:'004',name:'Shamata'}] },
    { code:'005', name:'Ndaragwa', wards:[{code:'001',name:'Kiriita'},{code:'002',name:'Mondo'},{code:'003',name:'Ndaragwa'},{code:'004',name:'Shamata'}] },
  ]},
  { code:'019', name:'Nyeri', constituencies:[
    { code:'001', name:'Tetu', wards:[{code:'001',name:'Dedan Kimathi'},{code:'002',name:'Wamagana'},{code:'003',name:'Aguthi/Gaaki'}] },
    { code:'002', name:'Kieni', wards:[{code:'001',name:'Mweiga'},{code:'002',name:'Mugunda'},{code:'003',name:'Gatarakwa'},{code:'004',name:'Thegu River'},{code:'005',name:'Kabaru'},{code:'006',name:'Gakawa'}] },
    { code:'003', name:'Mathira', wards:[{code:'001',name:'Ruguru'},{code:'002',name:'Karatina Town'},{code:'003',name:'Mahiga'},{code:'004',name:'Iria-Ini'},{code:'005',name:'Konyu'},{code:'006',name:'Chinga'},{code:'007',name:'Kariki'}] },
    { code:'004', name:'Othaya', wards:[{code:'001',name:'Gatitu/Muruguru'},{code:'002',name:'Gikondi'},{code:'003',name:'Muhito'},{code:'004',name:'Amboni'},{code:'005',name:'Githiga'}] },
    { code:'005', name:'Mukurwe-ini', wards:[{code:'001',name:'Giathi-Marigi'},{code:'002',name:'Gakui'},{code:'003',name:'Mukurwe-ini West'},{code:'004',name:'Mukurwe-ini East'}] },
    { code:'006', name:'Nyeri Town', wards:[{code:'001',name:'Rware'},{code:'002',name:'Gatitu'},{code:'003',name:'Ruringu'},{code:'004',name:'Kiganjo/Mathari'}] },
  ]},
  { code:'020', name:'Kirinyaga', constituencies:[
    { code:'001', name:'Mwea', wards:[{code:'001',name:'Mutithi'},{code:'002',name:'Kangai'},{code:'003',name:'Wamumu'},{code:'004',name:'Nyangati'},{code:'005',name:'Murinduko'},{code:'006',name:'Gathigiriri'},{code:'007',name:'Tebere'},{code:'008',name:'Karumandi'}] },
    { code:'002', name:'Gichugu', wards:[{code:'001',name:'Kabare'},{code:'002',name:'Kerugoya'},{code:'003',name:'Inoi'},{code:'004',name:'Kiine'}] },
    { code:'003', name:'Ndia', wards:[{code:'001',name:'Mukure'},{code:'002',name:'Kiini'},{code:'003',name:'Kariti'}] },
    { code:'004', name:'Kirinyaga Central', wards:[{code:'001',name:'Mutira'},{code:'002',name:'Kanyeki'},{code:'003',name:'Weru'},{code:'004',name:'Kamuthe'}] },
  ]},
  { code:'021', name:'Murang\'a', constituencies:[
    { code:'001', name:'Kangema', wards:[{code:'001',name:'Kanyenya-Ini'},{code:'002',name:'Muguru'},{code:'003',name:'Rwathia'}] },
    { code:'002', name:'Mathioya', wards:[{code:'001',name:'Gitugi'},{code:'002',name:'Kamacharia'},{code:'003',name:'Kiru'}] },
    { code:'003', name:'Kiharu', wards:[{code:'001',name:'Wangu'},{code:'002',name:'Mugoiri'},{code:'003',name:'Mbiri'},{code:'004',name:'Township'},{code:'005',name:'Murarandia'},{code:'006',name:'Gaturi'}] },
    { code:'004', name:'Kigumo', wards:[{code:'001',name:'Kahumbu'},{code:'002',name:'Muthithi'},{code:'003',name:'Kigumo'},{code:'004',name:'Kangari'},{code:'005',name:'Gituru'}] },
    { code:'005', name:'Maragua', wards:[{code:'001',name:'Kimorori/Wempa'},{code:'002',name:'Makuyu'},{code:'003',name:'Kambiti'},{code:'004',name:'Kamahuha'},{code:'005',name:'Ichagaki'},{code:'006',name:'Nginda'}] },
    { code:'006', name:'Kandara', wards:[{code:'001',name:'Ng\'araria'},{code:'002',name:'Muruka'},{code:'003',name:'Kagundu-Ini'},{code:'004',name:'Gaichanjiru'},{code:'005',name:'Ithiru'},{code:'006',name:'Ruchu'}] },
    { code:'007', name:'Gatanga', wards:[{code:'001',name:'Ithanga'},{code:'002',name:'Kakuzi/Mitubiri'},{code:'003',name:'Mugumo-Ini'},{code:'004',name:'Kihumbu-Ini'},{code:'005',name:'Gatanga'},{code:'006',name:'Kariara'}] },
  ]},
  { code:'022', name:'Kiambu', constituencies:[
    { code:'001', name:'Gatundu South', wards:[{code:'001',name:'Kiamwangi'},{code:'002',name:'Kiganjo'},{code:'003',name:'Ndarugu'},{code:'004',name:'Ngenda'}] },
    { code:'002', name:'Gatundu North', wards:[{code:'001',name:'Gituamba'},{code:'002',name:'Kariamu'},{code:'003',name:'Gitambaa'},{code:'004',name:'Kianji'}] },
    { code:'003', name:'Juja', wards:[{code:'001',name:'Murera'},{code:'002',name:'Theta'},{code:'003',name:'Juja'},{code:'004',name:'Wylde/Ondiri'},{code:'005',name:'Kalimoni/Gachororo'}] },
    { code:'004', name:'Thika Town', wards:[{code:'001',name:'Township'},{code:'002',name:'Kamenu'},{code:'003',name:'Hospital'},{code:'004',name:'Gatuanyaga'},{code:'005',name:'Ngoliba'}] },
    { code:'005', name:'Ruiru', wards:[{code:'001',name:'Gitothua'},{code:'002',name:'Biashara'},{code:'003',name:'Gatongora'},{code:'004',name:'Kahawa Sukari'},{code:'005',name:'Kahawa Wendani'},{code:'006',name:'Mwiki'},{code:'007',name:'Mwihoko'}] },
    { code:'006', name:'Githunguri', wards:[{code:'001',name:'Githunguri'},{code:'002',name:'Githiga'},{code:'003',name:'Ikinu'},{code:'004',name:'Ngewa'},{code:'005',name:'Komothai'}] },
    { code:'007', name:'Kiambu', wards:[{code:'001',name:'Kiambu Township'},{code:'002',name:'Ting\'ang\'a'},{code:'003',name:'Ndenderu'},{code:'004',name:'Kabete'},{code:'005',name:'Riabai'}] },
    { code:'008', name:'Kiambaa', wards:[{code:'001',name:'Cianda'},{code:'002',name:'Karuri'},{code:'003',name:'Kihara'},{code:'004',name:'Ndumberi'},{code:'005',name:'Tinganga'}] },
    { code:'009', name:'Kabete', wards:[{code:'001',name:'Gitaru'},{code:'002',name:'Muguga'},{code:'003',name:'Nyadhuna/Karai'},{code:'004',name:'Kabete'},{code:'005',name:'Uthiru'}] },
    { code:'010', name:'Kikuyu', wards:[{code:'001',name:'Karai'},{code:'002',name:'Sigona'},{code:'003',name:'Kikuyu'},{code:'004',name:'Kinoo'},{code:'005',name:'Ondiri'}] },
    { code:'011', name:'Limuru', wards:[{code:'001',name:'Bibirioni'},{code:'002',name:'Limuru Central'},{code:'003',name:'Ndeiya'},{code:'004',name:'Limuru East'},{code:'005',name:'Ngecha/Tigoni'}] },
    { code:'012', name:'Lari', wards:[{code:'001',name:'Kijabe'},{code:'002',name:'Nyanduma'},{code:'003',name:'Kinale'},{code:'004',name:'Kirenga'},{code:'005',name:'Lari/Kambaa'}] },
  ]},
  { code:'023', name:'Turkana', constituencies:[
    { code:'001', name:'Turkana North', wards:[{code:'001',name:'Kibish'},{code:'002',name:'Lapur'},{code:'003',name:'Kaeris'},{code:'004',name:'Lake Zone'},{code:'005',name:'Kaikor/Kaaleng'}] },
    { code:'002', name:'Turkana West', wards:[{code:'001',name:'Kakuma'},{code:'002',name:'Lopur'},{code:'003',name:'Letea'},{code:'004',name:'Songot'},{code:'005',name:'Kalobeyei'},{code:'006',name:'Lokichoggio'}] },
    { code:'003', name:'Turkana Central', wards:[{code:'001',name:'Kerio Delta'},{code:'002',name:'Lodwar Township'},{code:'003',name:'Nakalale'},{code:'004',name:'Kangatotha'},{code:'005',name:'Kalokol'}] },
    { code:'004', name:'Loima', wards:[{code:'001',name:'Kotaruk/Lobei'},{code:'002',name:'Turkwel'},{code:'003',name:'Loima'},{code:'004',name:'Lorugum'}] },
    { code:'005', name:'Turkana South', wards:[{code:'001',name:'Lokichar'},{code:'002',name:'Kainuk'},{code:'003',name:'Lokori/Kochodin'},{code:'004',name:'Kerio Delta'}] },
    { code:'006', name:'Turkana East', wards:[{code:'001',name:'Kapedo/Napeitom'},{code:'002',name:'Katilia'},{code:'003',name:'Lomelo'},{code:'004',name:'Morucakor'}] },
  ]},
  { code:'024', name:'West Pokot', constituencies:[
    { code:'001', name:'Kapenguria', wards:[{code:'001',name:'Sook'},{code:'002',name:'Suam'},{code:'003',name:'Masool'},{code:'004',name:'Mnagei'},{code:'005',name:'Kapenguria'},{code:'006',name:'Riwo'}] },
    { code:'002', name:'Sigor', wards:[{code:'001',name:'Sekerr'},{code:'002',name:'Masol'},{code:'003',name:'Pokot Central'},{code:'004',name:'Batei'}] },
    { code:'003', name:'Kacheliba', wards:[{code:'001',name:'Kodich'},{code:'002',name:'Kacheliba'},{code:'003',name:'Kasei'},{code:'004',name:'Alale'},{code:'005',name:'Lochom'}] },
    { code:'004', name:'Pokot South', wards:[{code:'001',name:'Parua'},{code:'002',name:'Laar'},{code:'003',name:'Lomut'},{code:'004',name:'Weiwei'}] },
  ]},
  { code:'025', name:'Samburu', constituencies:[
    { code:'001', name:'Samburu West', wards:[{code:'001',name:'Suguta Marmar'},{code:'002',name:'Maralal'},{code:'003',name:'Loosuk'},{code:'004',name:'Poro'}] },
    { code:'002', name:'Samburu North', wards:[{code:'001',name:'Baragoi'},{code:'002',name:'Wamba North'},{code:'003',name:'Wamba West'},{code:'004',name:'Wamba East'}] },
    { code:'003', name:'Samburu East', wards:[{code:'001',name:'Archer\'s Post'},{code:'002',name:'Merti'},{code:'003',name:'Karare'}] },
  ]},
  { code:'026', name:'Trans Nzoia', constituencies:[
    { code:'001', name:'Kwanza', wards:[{code:'001',name:'Keiyo'},{code:'002',name:'Bidii'},{code:'003',name:'Matisi'},{code:'004',name:'Tuwani'}] },
    { code:'002', name:'Endebess', wards:[{code:'001',name:'Endebess'},{code:'002',name:'Metkei'},{code:'003',name:'Central Cherangany/Loyamorok'},{code:'004',name:'Matumbei'}] },
    { code:'003', name:'Saboti', wards:[{code:'001',name:'Kinyoro'},{code:'002',name:'Matisi'},{code:'003',name:'Tuwani'},{code:'004',name:'Saboti'},{code:'005',name:'Machewa'}] },
    { code:'004', name:'Kiminini', wards:[{code:'001',name:'Kapomboi'},{code:'002',name:'Kwanza'},{code:'003',name:'Keiyo'},{code:'004',name:'Bidii'}] },
    { code:'005', name:'Cherangany', wards:[{code:'001',name:'Kaplamai'},{code:'002',name:'Motosiet'},{code:'003',name:'Cherangany/Suwerwa'},{code:'004',name:'Sitatunga'},{code:'005',name:'Labot/Karelach'}] },
  ]},
  { code:'027', name:'Uasin Gishu', constituencies:[
    { code:'001', name:'Soy', wards:[{code:'001',name:'Moi\'s Bridge'},{code:'002',name:'Kipsomba'},{code:'003',name:'Ziwa'},{code:'004',name:'Ainabkoi'},{code:'005',name:'Kaptagat'}] },
    { code:'002', name:'Turbo', wards:[{code:'001',name:'Turbo'},{code:'002',name:'Ngenyilel'},{code:'003',name:'Tapsagoi'},{code:'004',name:'Kamagut'},{code:'005',name:'Huruma'}] },
    { code:'003', name:'Moiben', wards:[{code:'001',name:'Moiben'},{code:'002',name:'Kuinet/Kapsuswa'},{code:'003',name:'Tembelio'},{code:'004',name:'Sergoit'},{code:'005',name:'Karuna/Meibeki'}] },
    { code:'004', name:'Ainabkoi', wards:[{code:'001',name:'Ainabkoi/Olare'},{code:'002',name:'Kapsoya'},{code:'003',name:'Kimumu'}] },
    { code:'005', name:'Kapseret', wards:[{code:'001',name:'Langas'},{code:'002',name:'Racecourse'},{code:'003',name:'Kipkenyo'},{code:'004',name:'Ngeria'},{code:'005',name:'Megun'}] },
    { code:'006', name:'Kesses', wards:[{code:'001',name:'Tarakwa'},{code:'002',name:'Megun'},{code:'003',name:'Tulwet/Chuiyat'},{code:'004',name:'Soy'}] },
  ]},
  { code:'028', name:'Elgeyo Marakwet', constituencies:[
    { code:'001', name:'Marakwet East', wards:[{code:'001',name:'Lelan'},{code:'002',name:'Soy'},{code:'003',name:'Moiben'},{code:'004',name:'Kapyego'}] },
    { code:'002', name:'Marakwet West', wards:[{code:'001',name:'Arror'},{code:'002',name:'Chebiemit'},{code:'003',name:'Endo'}] },
    { code:'003', name:'Keiyo North', wards:[{code:'001',name:'Emsoo'},{code:'002',name:'Kamariny'},{code:'003',name:'Kaptarakwa'},{code:'004',name:'Tambach'}] },
    { code:'004', name:'Keiyo South', wards:[{code:'001',name:'Roroek'},{code:'002',name:'Chepkorio'},{code:'003',name:'Soy'},{code:'004',name:'Kabiemit'}] },
  ]},
  { code:'029', name:'Nandi', constituencies:[
    { code:'001', name:'Tinderet', wards:[{code:'001',name:'Songhor/Soba'},{code:'002',name:'Melelo'},{code:'003',name:'Kobujoi'},{code:'004',name:'Chombei'}] },
    { code:'002', name:'Aldai', wards:[{code:'001',name:'Kabwareng'},{code:'002',name:'Terik'},{code:'003',name:'Kemeloi-Maraba'},{code:'004',name:'Kobujoi'},{code:'005',name:'Ndalat'},{code:'006',name:'Ngechek'}] },
    { code:'003', name:'Nandi Hills', wards:[{code:'001',name:'Nandi Hills'},{code:'002',name:'Kapchorwa'},{code:'003',name:'Chepkunyuk'},{code:'004',name:'Ol\'lessos'}] },
    { code:'004', name:'Chesumei', wards:[{code:'001',name:'Lelmokwo/Ngechek'},{code:'002',name:'Chemundu/Kapure'},{code:'003',name:'Koyo-Ndurio'},{code:'004',name:'Kaptel/Kamobo'}] },
    { code:'005', name:'Emgwen', wards:[{code:'001',name:'Canaan'},{code:'002',name:'Chepkumia'},{code:'003',name:'Kapkures'},{code:'004',name:'Ngechek'}] },
    { code:'006', name:'Mosop', wards:[{code:'001',name:'Kabisaga'},{code:'002',name:'Chepterwai'},{code:'003',name:'Kimasass'},{code:'004',name:'Chemundu'},{code:'005',name:'Ndalat'}] },
  ]},
  { code:'030', name:'Baringo', constituencies:[
    { code:'001', name:'Tiaty', wards:[{code:'001',name:'Tirioko'},{code:'002',name:'Kolowa'},{code:'003',name:'Ribkwo'},{code:'004',name:'Silale'},{code:'005',name:'Loiyamorok'},{code:'006',name:'Tangulbei/Korossi'}] },
    { code:'002', name:'Baringo North', wards:[{code:'001',name:'Barwessa'},{code:'002',name:'Kabarnet'},{code:'003',name:'Saimo/Soi'},{code:'004',name:'Saimo/Kipsaraman'}] },
    { code:'003', name:'Baringo Central', wards:[{code:'001',name:'Kabimoi'},{code:'002',name:'Lembus'},{code:'003',name:'Lembus Kwen'},{code:'004',name:'Ravine'},{code:'005',name:'Mumberes/Maji Mazuri'}] },
    { code:'004', name:'Baringo South', wards:[{code:'001',name:'Eldama Ravine'},{code:'002',name:'Lembus/Perkerra'},{code:'003',name:'Emining'},{code:'004',name:'Koibatek'}] },
    { code:'005', name:'Mogotio', wards:[{code:'001',name:'Mogotio'},{code:'002',name:'Emining'},{code:'003',name:'Kisanana'}] },
    { code:'006', name:'Eldama Ravine', wards:[{code:'001',name:'Ravine'},{code:'002',name:'Mumberes/Maji Mazuri'},{code:'003',name:'Lembus'},{code:'004',name:'Koibatek'}] },
  ]},
  { code:'031', name:'Laikipia', constituencies:[
    { code:'001', name:'Laikipia West', wards:[{code:'001',name:'Ol-Moran'},{code:'002',name:'Marmanet'},{code:'003',name:'Githiga'}] },
    { code:'002', name:'Laikipia East', wards:[{code:'001',name:'Tigithi'},{code:'002',name:'Thingithu'},{code:'003',name:'Nturukuma'},{code:'004',name:'Dol Dol'}] },
    { code:'003', name:'Laikipia North', wards:[{code:'001',name:'Rumuruti Township'},{code:'002',name:'Githiga'},{code:'003',name:'Igwamiti'},{code:'004',name:'Salama'}] },
  ]},
  { code:'032', name:'Nakuru', constituencies:[
    { code:'001', name:'Molo', wards:[{code:'001',name:'Turi'},{code:'002',name:'Molo'},{code:'003',name:'Mariashoni'},{code:'004',name:'Elburgon'},{code:'005',name:'Moire'}] },
    { code:'002', name:'Njoro', wards:[{code:'001',name:'Njoro'},{code:'002',name:'Mauche'},{code:'003',name:'Kihingo'},{code:'004',name:'Ihururu'},{code:'005',name:'Mauche'}] },
    { code:'003', name:'Naivasha', wards:[{code:'001',name:'Viwanda'},{code:'002',name:'Hells Gate'},{code:'003',name:'Lake View'},{code:'004',name:'Mai Mahiu'},{code:'005',name:'Maiella'},{code:'006',name:'Olkaria'},{code:'007',name:'Naivasha East'},{code:'008',name:'Kinungi'}] },
    { code:'004', name:'Gilgil', wards:[{code:'001',name:'Elementaita'},{code:'002',name:'Gilgil'},{code:'003',name:'Mbaruk/Eburu'},{code:'004',name:'Malewa West'}] },
    { code:'005', name:'Kuresoi South', wards:[{code:'001',name:'Amalo'},{code:'002',name:'Keringet'},{code:'003',name:'Kiptagich'},{code:'004',name:'Tinet'}] },
    { code:'006', name:'Kuresoi North', wards:[{code:'001',name:'Kiptororo'},{code:'002',name:'Nyota'},{code:'003',name:'Sirikwa'},{code:'004',name:'Kamara'}] },
    { code:'007', name:'Subukia', wards:[{code:'001',name:'Subukia'},{code:'002',name:'Waseges'},{code:'003',name:'Kabazi'}] },
    { code:'008', name:'Rongai', wards:[{code:'001',name:'Rongai'},{code:'002',name:'Mosop'},{code:'003',name:'Visoi'},{code:'004',name:'Menengai West'},{code:'005',name:'Soin'}] },
    { code:'009', name:'Bahati', wards:[{code:'001',name:'Bahati'},{code:'002',name:'Dundori'},{code:'003',name:'Kabazi'},{code:'004',name:'Lanet/Umoja'}] },
    { code:'010', name:'Nakuru Town West', wards:[{code:'001',name:'Barut'},{code:'002',name:'London'},{code:'003',name:'Kaptembwo'},{code:'004',name:'Kapkures'},{code:'005',name:'Nakuru East'}] },
    { code:'011', name:'Nakuru Town East', wards:[{code:'001',name:'Biashara'},{code:'002',name:'Kivumbini'},{code:'003',name:'Flamingo'},{code:'004',name:'Menengai'},{code:'005',name:'Nakuru East'}] },
  ]},
  { code:'033', name:'Narok', constituencies:[
    { code:'001', name:'Kilgoris', wards:[{code:'001',name:'Angata Barikoi'},{code:'002',name:'Shankoe'},{code:'003',name:'Kimintet'},{code:'004',name:'Lolgorian'}] },
    { code:'002', name:'Emurua Dikirr', wards:[{code:'001',name:'Ilkisonko'},{code:'002',name:'Keekonyokie'},{code:'003',name:'Mosiro'},{code:'004',name:'Entosambu'}] },
    { code:'003', name:'Narok North', wards:[{code:'001',name:'Olposimoru'},{code:'002',name:'Olokurto'},{code:'003',name:'Narok Town'},{code:'004',name:'Nkareta'},{code:'005',name:'Olorropil'},{code:'006',name:'Melili'}] },
    { code:'004', name:'Narok East', wards:[{code:'001',name:'Ildamat'},{code:'002',name:'Keekonyokie'},{code:'003',name:'Melili'},{code:'004',name:'Suswa'}] },
    { code:'005', name:'Narok South', wards:[{code:'001',name:'Majimoto/Naroosura'},{code:'002',name:'Olkeri'},{code:'003',name:'Sagamian'},{code:'004',name:'Nkararo'},{code:'005',name:'Loita'}] },
    { code:'006', name:'Narok West', wards:[{code:'001',name:'Mara'},{code:'002',name:'Siana'},{code:'003',name:'Koyiaki'}] },
  ]},
  { code:'034', name:'Kajiado', constituencies:[
    { code:'001', name:'Kajiado North', wards:[{code:'001',name:'Erdemann'},{code:'002',name:'Olkeri'},{code:'003',name:'Ongata Rongai'},{code:'004',name:'Ngong'},{code:'005',name:'Oloolua'}] },
    { code:'002', name:'Kajiado Central', wards:[{code:'001',name:'Purko'},{code:'002',name:'Dalalekutuk'},{code:'003',name:'Mbirikani/Eselenkei'}] },
    { code:'003', name:'Kajiado East', wards:[{code:'001',name:'Kaputiei North'},{code:'002',name:'Kitengela'},{code:'003',name:'Oloitokitok'},{code:'004',name:'Kenyawa-Poka'},{code:'005',name:'Imaroro'}] },
    { code:'004', name:'Kajiado West', wards:[{code:'001',name:'Keekonyokie'},{code:'002',name:'Iloodokilani'},{code:'003',name:'Magadi'},{code:'004',name:'Ewuaso Oonkidong\'i'},{code:'005',name:'Mosiro'}] },
    { code:'005', name:'Kajiado South', wards:[{code:'001',name:'Entosambu'},{code:'002',name:'Entasekera'},{code:'003',name:'Sajiloni'},{code:'004',name:'Imbirikani'},{code:'005',name:'Ildamat'}] },
  ]},
  { code:'035', name:'Kericho', constituencies:[
    { code:'001', name:'Kipkelion East', wards:[{code:'001',name:'Chepseon'},{code:'002',name:'Tendeno/Sorget'},{code:'003',name:'Kunyak'},{code:'004',name:'Kabianga'},{code:'005',name:'Kipkelion Town'}] },
    { code:'002', name:'Kipkelion West', wards:[{code:'001',name:'Kipkelion Central'},{code:'002',name:'Tebesonik'},{code:'003',name:'Sigor/Barsiele'}] },
    { code:'003', name:'Ainamoi', wards:[{code:'001',name:'Ainamoi'},{code:'002',name:'Kapkugerwet'},{code:'003',name:'Kapsaos'}] },
    { code:'004', name:'Bureti', wards:[{code:'001',name:'Cheplanget'},{code:'002',name:'Kapkatet'},{code:'003',name:'Sigor'},{code:'004',name:'Chemaner'},{code:'005',name:'Koiwa'}] },
    { code:'005', name:'Belgut', wards:[{code:'001',name:'Kabianga'},{code:'002',name:'Kapsuser'},{code:'003',name:'Kembu'},{code:'004',name:'Londiani'},{code:'005',name:'Kiptuiyat'},{code:'006',name:'Cheboin'}] },
    { code:'006', name:'Sigowet/Soin', wards:[{code:'001',name:'Soliat'},{code:'002',name:'Soin'},{code:'003',name:'Sigowet'},{code:'004',name:'Kamasian'}] },
  ]},
  { code:'036', name:'Bomet', constituencies:[
    { code:'001', name:'Sotik', wards:[{code:'001',name:'Ndanai/Abosi'},{code:'002',name:'Chemagel'},{code:'003',name:'Kipreres'},{code:'004',name:'Siguom'},{code:'005',name:'Longisa'}] },
    { code:'002', name:'Chepalungu', wards:[{code:'001',name:'Siongiroi'},{code:'002',name:'Metkei/St. Teresa'},{code:'003',name:'Chesoen'},{code:'004',name:'Mulot'}] },
    { code:'003', name:'Bomet East', wards:[{code:'001',name:'Mutarakwa'},{code:'002',name:'Sigor/St. Teresa'},{code:'003',name:'Chemaner'},{code:'004',name:'Siongiroi'}] },
    { code:'004', name:'Bomet Central', wards:[{code:'001',name:'Silibwet Township'},{code:'002',name:'Ndaraweta'},{code:'003',name:'Chesoen'},{code:'004',name:'Singorwet'}] },
    { code:'005', name:'Konoin', wards:[{code:'001',name:'Mogogosiek'},{code:'002',name:'Kembu'},{code:'003',name:'Boito'},{code:'004',name:'Cheborge'}] },
  ]},
  { code:'037', name:'Kakamega', constituencies:[
    { code:'001', name:'Lugari', wards:[{code:'001',name:'Mautuma'},{code:'002',name:'Lugari'},{code:'003',name:'Lumakanda'},{code:'004',name:'Chekalini'},{code:'005',name:'Chevaywa'},{code:'006',name:'Mukuyuni'}] },
    { code:'002', name:'Likuyani', wards:[{code:'001',name:'Sango'},{code:'002',name:'Nzoia'},{code:'003',name:'Kongoni'},{code:'004',name:'Likuyani'},{code:'005',name:'Sinoko'}] },
    { code:'003', name:'Malava', wards:[{code:'001',name:'Shirere'},{code:'002',name:'Manda'},{code:'003',name:'Mahiakalo'},{code:'004',name:'East Kabras'},{code:'005',name:'Butali/Chegulo'},{code:'006',name:'North Kabras'},{code:'007',name:'West Kabras'},{code:'008',name:'Chemuche'}] },
    { code:'004', name:'Lurambi', wards:[{code:'001',name:'Sheywe'},{code:'002',name:'Mahiakalo'},{code:'003',name:'Sichirai'},{code:'004',name:'Butsotso East'},{code:'005',name:'Butsotso South'},{code:'006',name:'Butsotso Central'}] },
    { code:'005', name:'Navakholo', wards:[{code:'001',name:'Ingotse/Matungu'},{code:'002',name:'Namamali'},{code:'003',name:'Navakholo'},{code:'004',name:'West Bunyore'},{code:'005',name:'Bunyore East'}] },
    { code:'006', name:'Mumias West', wards:[{code:'001',name:'Lusheya/Lubinu'},{code:'002',name:'Malaha/Isongo/Makunga'},{code:'003',name:'East Wanga'},{code:'004',name:'Ogelo'}] },
    { code:'007', name:'Mumias East', wards:[{code:'001',name:'Lusheya'},{code:'002',name:'Malaha/Isongo'},{code:'003',name:'East Wanga'},{code:'004',name:'Nabuyole'},{code:'005',name:'Koyonzo'}] },
    { code:'008', name:'Matungu', wards:[{code:'001',name:'Kholera'},{code:'002',name:'Mayoni'},{code:'003',name:'Namamali'},{code:'004',name:'Khalaba'},{code:'005',name:'Makunga'},{code:'006',name:'Ebukanga'},{code:'007',name:'Budonga'},{code:'008',name:'Busibwabo'}] },
    { code:'009', name:'Butere', wards:[{code:'001',name:'Marama West'},{code:'002',name:'Marama Central'},{code:'003',name:'Marama South'},{code:'004',name:'South Wanga'},{code:'005',name:'North East Bunyore'}] },
    { code:'010', name:'Khwisero', wards:[{code:'001',name:'Kisa North'},{code:'002',name:'Kisa East'},{code:'003',name:'Kisa West'},{code:'004',name:'Kisa Central'},{code:'005',name:'West Bunyore'}] },
    { code:'011', name:'Shinyalu', wards:[{code:'001',name:'Isukha North'},{code:'002',name:'Isukha South'},{code:'003',name:'Isukha East'},{code:'004',name:'Isukha West'},{code:'005',name:'Isukha Central'},{code:'006',name:'Murhanda'}] },
    { code:'012', name:'Ikolomani', wards:[{code:'001',name:'Idakho South'},{code:'002',name:'Idakho East'},{code:'003',name:'Idakho North'},{code:'004',name:'Idakho Central'}] },
  ]},
  { code:'038', name:'Vihiga', constituencies:[
    { code:'001', name:'Vihiga', wards:[{code:'001',name:'Lugaga/Wamuluma'},{code:'002',name:'South Maragoli'},{code:'003',name:'Central Maragoli'},{code:'004',name:'Mungoma'}] },
    { code:'002', name:'Sabatia', wards:[{code:'001',name:'Ivoho/Mahanga'},{code:'002',name:'Chavakali'},{code:'003',name:'North Maragoli'},{code:'004',name:'Wodanga'},{code:'005',name:'Sabatia'}] },
    { code:'003', name:'Hamisi', wards:[{code:'001',name:'Shiru'},{code:'002',name:'Gisambai'},{code:'003',name:'Shamakhokho'},{code:'004',name:'Banja'},{code:'005',name:'Muhudu'},{code:'006',name:'Tambua'},{code:'007',name:'Jepkoyai'}] },
    { code:'004', name:'Luanda', wards:[{code:'001',name:'Emabungo'},{code:'002',name:'North East Bunyore'},{code:'003',name:'Central Bunyore'},{code:'004',name:'West Bunyore'}] },
    { code:'005', name:'Emuhaya', wards:[{code:'001',name:'North East Bunyore'},{code:'002',name:'Central Bunyore'},{code:'003',name:'West Bunyore'},{code:'004',name:'Emabungo'}] },
  ]},
  { code:'039', name:'Bungoma', constituencies:[
    { code:'001', name:'Mt. Elgon', wards:[{code:'001',name:'Cheptais'},{code:'002',name:'Chesikaki'},{code:'003',name:'Chepyuk'},{code:'004',name:'Kapkateny'},{code:'005',name:'Kopsiro'},{code:'006',name:'Kome'}] },
    { code:'002', name:'Sirisia', wards:[{code:'001',name:'Namwela'},{code:'002',name:'Malakisi/South Kulisiru'},{code:'003',name:'Lwandanyi'}] },
    { code:'003', name:'Kabuchai', wards:[{code:'001',name:'Kabuchai/Chwele'},{code:'002',name:'West Nalondo'},{code:'003',name:'Bwake/Luuya'},{code:'004',name:'Mukuyuni'}] },
    { code:'004', name:'Bumula', wards:[{code:'001',name:'West Bukusu'},{code:'002',name:'Khasoko'},{code:'003',name:'Kabula'},{code:'004',name:'Kimaeti'},{code:'005',name:'East Bukusu'},{code:'006',name:'South Bukusu'},{code:'007',name:'Bumula'}] },
    { code:'005', name:'Kanduyi', wards:[{code:'001',name:'Township'},{code:'002',name:'Bukembe West'},{code:'003',name:'Bukembe East'},{code:'004',name:'Hospital'},{code:'005',name:'Musikoma'},{code:'006',name:'East Sangalo'},{code:'007',name:'West Sangalo'},{code:'008',name:'Marakaru/Tuuti'}] },
    { code:'006', name:'Webuye East', wards:[{code:'001',name:'Mihuu'},{code:'002',name:'Ndivisi'},{code:'003',name:'Maraka'}] },
    { code:'007', name:'Webuye West', wards:[{code:'001',name:'Matulo'},{code:'002',name:'Bokoli'},{code:'003',name:'Kocholia'},{code:'004',name:'Misikhu'}] },
    { code:'008', name:'Tongaren', wards:[{code:'001',name:'Naitiri/Kabuyefwe'},{code:'002',name:'Milima'},{code:'003',name:'Ndalu/Tabani'},{code:'004',name:'Tongaren'},{code:'005',name:'Soysambu/Mitua'}] },
    { code:'009', name:'Kimilili', wards:[{code:'001',name:'Kimilili'},{code:'002',name:'Kibingei'},{code:'003',name:'Maeni'},{code:'004',name:'Kamukuywa'}] },
  ]},
  { code:'040', name:'Busia', constituencies:[
    { code:'001', name:'Teso North', wards:[{code:'001',name:'Malaba Central'},{code:'002',name:'Malaba North'},{code:'003',name:"Ang'urai North"},{code:'004',name:"Ang'urai South"},{code:'005',name:"Ang'urai East"}] },
    { code:'002', name:'Teso South', wards:[{code:'001',name:"Ang'urai South"},{code:'002',name:'Malaba South'},{code:'003',name:'Malaba West'},{code:'004',name:'Amukura East'},{code:'005',name:'Amukura West'},{code:'006',name:'Amukura Central'}] },
    { code:'003', name:'Nambale', wards:[{code:'001',name:'Nambale Township'},{code:'002',name:'Bukhayo North/Walatsi'},{code:'003',name:'Bukhayo East'},{code:'004',name:'Bukhayo Central'}] },
    { code:'004', name:'Matayos', wards:[{code:'001',name:'Burumba'},{code:'002',name:'West Bukhayo'},{code:'003',name:'Elugulu'},{code:'004',name:'Kingandole'},{code:'005',name:'Mayenje'}] },
    { code:'005', name:'Butula', wards:[{code:'001',name:'Elugulu'},{code:'002',name:'Butsotso'},{code:'003',name:'Mundika'},{code:'004',name:'Namboboto Nangwe'},{code:'005',name:'Marachi Central'},{code:'006',name:'Port Victoria'}] },
    { code:'006', name:'Funyula', wards:[{code:'001',name:'Mundika'},{code:'002',name:'Namboboto Nangwe'},{code:'003',name:'Nangwe'},{code:'004',name:'Funyula'},{code:'005',name:'Butula'}] },
    { code:'007', name:'Bunyala', wards:[{code:'001',name:'West Bunyala'},{code:'002',name:'East Bunyala'},{code:'003',name:'North Bunyala'},{code:'004',name:'South Bunyala'}] },
  ]},
  { code:'041', name:'Siaya', constituencies:[
    { code:'001', name:'Rarieda', wards:[{code:'001',name:'East Asembo'},{code:'002',name:'West Asembo'},{code:'003',name:'North Uyoma'},{code:'004',name:'South Uyoma'},{code:'005',name:'West Uyoma'}] },
    { code:'002', name:'Gem', wards:[{code:'001',name:'Central Gem'},{code:'002',name:'East Gem'},{code:'003',name:'West Gem'},{code:'004',name:'North Gem'},{code:'005',name:'Yala Township'},{code:'006',name:'Sifuyo'}] },
    { code:'003', name:'Bondo', wards:[{code:'001',name:'East Yimbo'},{code:'002',name:'Got Regea'},{code:'003',name:'North Yimbo'},{code:'004',name:'West Yimbo'},{code:'005',name:'Central Yimbo'},{code:'006',name:'Yimbo East'}] },
    { code:'004', name:'Ugenya', wards:[{code:'001',name:'West Ugenya'},{code:'002',name:'Ugenya East'},{code:'003',name:'Ukwala'},{code:'004',name:'North Ugenya'}] },
    { code:'005', name:'Ugunja', wards:[{code:'001',name:'Sigomre'},{code:'002',name:'West Ugenya'},{code:'003',name:'North Ugenya'},{code:'004',name:'Sidindi'},{code:'005',name:'Ugunja'}] },
    { code:'006', name:'Alego Usonga', wards:[{code:'001',name:'Central Alego'},{code:'002',name:'Siaya Township'},{code:'003',name:'Usonga'},{code:'004',name:'West Alego'},{code:'005',name:'North Alego'},{code:'006',name:'South Alego'}] },
  ]},
  { code:'042', name:'Kisumu', constituencies:[
    { code:'001', name:'Kisumu East', wards:[{code:'001',name:'Kolwa East'},{code:'002',name:'Miwani'},{code:'003',name:'Omgando/Masogo'},{code:'004',name:'Nyalenda A'},{code:'005',name:'Nyalenda B'}] },
    { code:'002', name:'Kisumu West', wards:[{code:'001',name:'South West Kisumu'},{code:'002',name:'Central Kisumu'},{code:'003',name:'Kisumu North'},{code:'004',name:'West Kisumu'},{code:'005',name:'Railways'}] },
    { code:'003', name:'Kisumu Central', wards:[{code:'001',name:'Railways'},{code:'002',name:'Migosi'},{code:'003',name:'Shaurimoyo Kaloleni'},{code:'004',name:'Market Milimani'},{code:'005',name:'Kondele'},{code:'006',name:'Central Kisumu'}] },
    { code:'004', name:'Seme', wards:[{code:'001',name:'West Seme'},{code:'002',name:'Central Seme'},{code:'003',name:'East Seme'},{code:'004',name:'North Seme'}] },
    { code:'005', name:'Nyando', wards:[{code:'001',name:'East Kano/Wawidhi'},{code:'002',name:'Awasi/Onjiko'},{code:'003',name:'Ahero'},{code:'004',name:'Kabonyo/Kanyagwal'},{code:'005',name:'Kobura'}] },
    { code:'006', name:'Muhoroni', wards:[{code:'001',name:'Miwani'},{code:'002',name:'Omgando/Masogo'},{code:'003',name:'Chemelil/Songhor'},{code:'004',name:'Muhoroni/Koru'},{code:'005',name:'Tamu'},{code:'006',name:'Fort Ternan'}] },
    { code:'007', name:'Nyakach', wards:[{code:'001',name:'North West Nyakach'},{code:'002',name:'South East Nyakach'},{code:'003',name:'West Nyakach'},{code:'004',name:'Central Nyakach'},{code:'005',name:'East Nyakach'}] },
  ]},
  { code:'043', name:'Homa Bay', constituencies:[
    { code:'001', name:'Kasipul', wards:[{code:'001',name:'West Kasipul'},{code:'002',name:'Central Kasipul'},{code:'003',name:'East Kasipul'},{code:'004',name:'South Kasipul'},{code:'005',name:'Ruma/Kaksingri'}] },
    { code:'002', name:'Kabondo Kasipul', wards:[{code:'001',name:'Kabondo East'},{code:'002',name:'Kabondo West'},{code:'003',name:'Kokwanyo/Kakelo'},{code:'004',name:'Kojwach'}] },
    { code:'003', name:'Karachuonyo', wards:[{code:'001',name:'North Karachuonyo'},{code:'002',name:'West Karachuonyo'},{code:'003',name:'Central'},{code:'004',name:'Kanyaluo'},{code:'005',name:'Kibiri'},{code:'006',name:'East Karachuonyo'},{code:'007',name:'Kendu Bay Town'}] },
    { code:'004', name:'Rangwe', wards:[{code:'001',name:'East Gem'},{code:'002',name:'West Gem'},{code:'003',name:'Central Gem'},{code:'004',name:'North Gem'}] },
    { code:'005', name:'Homa Bay Town', wards:[{code:'001',name:'Homa Bay Central'},{code:'002',name:'Homa Bay Arujo'},{code:'003',name:'Homa Bay West'},{code:'004',name:'Homa Bay East'}] },
    { code:'006', name:'Ndhiwa', wards:[{code:'001',name:'Kwabwai'},{code:'002',name:'Kanyadhiang'},{code:'003',name:'Kanyikela'},{code:'004',name:'North Ndhiwa'},{code:'005',name:'Kanyaluo'}] },
    { code:'007', name:'Mbita', wards:[{code:'001',name:'Mfangano Island'},{code:'002',name:'Rusinga Island'},{code:'003',name:'Lambwe'},{code:'004',name:'Gwassi South'},{code:'005',name:'Gwassi North'}] },
    { code:'008', name:'Suba North', wards:[{code:'001',name:'Gwassi South'},{code:'002',name:'Gwassi North'},{code:'003',name:'Kaksingri West'},{code:'004',name:'Ruma/Kaksingri'}] },
  ]},
  { code:'044', name:'Migori', constituencies:[
    { code:'001', name:'Rongo', wards:[{code:'001',name:'North Kamagambo'},{code:'002',name:'Central Kamagambo'},{code:'003',name:'East Kamagambo'},{code:'004',name:'South Kamagambo'}] },
    { code:'002', name:'Awendo', wards:[{code:'001',name:'North Sakwa'},{code:'002',name:'South Sakwa'},{code:'003',name:'Central Sakwa'},{code:'004',name:'East Sakwa'}] },
    { code:'003', name:'Suna East', wards:[{code:'001',name:'Wiga'},{code:'002',name:'Mwanda'},{code:'003',name:'Wasimbete'},{code:'004',name:'God Jope'},{code:'005',name:'Suna Central'},{code:'006',name:'Kwa'},{code:'007',name:'Kakrao'}] },
    { code:'004', name:'Suna West', wards:[{code:'001',name:'Wiga'},{code:'002',name:'Mwanda'},{code:'003',name:'Wasimbete'},{code:'004',name:'God Jope'},{code:'005',name:'Suna Central'}] },
    { code:'005', name:'Nyatike', wards:[{code:'001',name:"Kachieng'"},{code:'002',name:'Kanyasa'},{code:'003',name:'North Kadem'},{code:'004',name:'South Kadem'},{code:'005',name:'Macalder/Kanyarwanda'},{code:'006',name:'Kaler'},{code:'007',name:'Got Kachola'}] },
    { code:'006', name:'Uriri', wards:[{code:'001',name:'West Kanyamkago'},{code:'002',name:'North Kanyamkago'},{code:'003',name:'Central Kanyamkago'},{code:'004',name:'East Kanyamkago'},{code:'005',name:'South Kanyamkago'}] },
    { code:'007', name:'Kuria East', wards:[{code:'001',name:'Gokeharaka/Getambwega'},{code:'002',name:'Ntimaru West'},{code:'003',name:'Ntimaru East'},{code:'004',name:'Nyabasi East'},{code:'005',name:'Nyabasi West'}] },
    { code:'008', name:'Kuria West', wards:[{code:'001',name:'Masaba South'},{code:'002',name:'Isibania'},{code:'003',name:'Makerero'},{code:'004',name:'Tagare'},{code:'005',name:'Bokimonge'},{code:'006',name:'Mabera'}] },
  ]},
  { code:'045', name:'Kisii', constituencies:[
    { code:'001', name:'Bonchari', wards:[{code:'001',name:'Bogiakumu'},{code:'002',name:'Riana'},{code:'003',name:'Bonchari'},{code:'004',name:'South Mugirango'},{code:'005',name:'Borabu/Chitago'}] },
    { code:'002', name:'South Mugirango', wards:[{code:'001',name:'Bogiakumu'},{code:'002',name:'Getenga'},{code:'003',name:'Metembe'},{code:'004',name:'Magombo'},{code:'005',name:'Gesima'}] },
    { code:'003', name:'Bomachoge Borabu', wards:[{code:'001',name:'Kitise/Kache'},{code:'002',name:'Ichuni'},{code:'003',name:'Moticho'},{code:'004',name:'Gesieka'},{code:'005',name:'Nyacheki'}] },
    { code:'004', name:'Bobasi', wards:[{code:'001',name:'Nyacheki'},{code:'002',name:'Masige West'},{code:'003',name:'Masige East'},{code:'004',name:'Basi Central'},{code:'005',name:"Boitang'are"},{code:'006',name:'Maji Moto/Nyabikondo'}] },
    { code:'005', name:'Bomachoge Chache', wards:[{code:'001',name:'Magenche'},{code:'002',name:'Gesabakwa'},{code:'003',name:'Chamage'},{code:'004',name:'Boochi/Tendere'},{code:'005',name:'Bomariba'}] },
    { code:'006', name:'Nyaribari Masaba', wards:[{code:'001',name:'Nyamarambe'},{code:'002',name:'Gesima'},{code:'003',name:'Masimba'},{code:'004',name:'Gesusu'},{code:'005',name:'Iranda'}] },
    { code:'007', name:'Nyaribari Chache', wards:[{code:'001',name:'Bobaracho'},{code:'002',name:'Keumbu'},{code:'003',name:'Kiogoro'},{code:'004',name:'Birongo'},{code:'005',name:'Ibeno'},{code:'006',name:'Kisii Central'}] },
    { code:'008', name:'Kitutu Chache North', wards:[{code:'001',name:'Menyinkwa'},{code:'002',name:'Marani'},{code:'003',name:'Kegogi'},{code:'004',name:'Bassi North'},{code:'005',name:'Nyakoe'}] },
    { code:'009', name:'Kitutu Chache South', wards:[{code:'001',name:'Bogusero'},{code:'002',name:"Boikang'a"},{code:'003',name:'Nyatieko'},{code:'004',name:'Ikonge'},{code:'005',name:'Mosocho'}] },
  ]},
  { code:'046', name:'Nyamira', constituencies:[
    { code:'001', name:'Kitutu Masaba', wards:[{code:'001',name:'Rigoma'},{code:'002',name:'Gachuba'},{code:'003',name:'Kemera'},{code:'004',name:'Magwagwa'},{code:'005',name:'Ekerenyo'}] },
    { code:'002', name:'West Mugirango', wards:[{code:'001',name:'Bonyamatoppo'},{code:'002',name:'Bokeira'},{code:'003',name:'Magwagwa'},{code:'004',name:'Metembe'},{code:'005',name:'Bogetenga'}] },
    { code:'003', name:'North Mugirango', wards:[{code:'001',name:'Ekerenyo'},{code:'002',name:'Manga'},{code:'003',name:'Gesima'},{code:'004',name:'Nyansiongo'}] },
    { code:'004', name:'Borabu', wards:[{code:'001',name:'Bosamaro'},{code:'002',name:'Bonyamatoppo'},{code:'003',name:'Bokeira'},{code:'004',name:'Itibo'},{code:'005',name:'Kiabonyoru'}] },
  ]},
  { code:'047', name:'Nairobi', constituencies:[
    { code:'001', name:'Westlands', wards:[{code:'001',name:'Kitisuru'},{code:'002',name:'Parklands/Highridge'},{code:'003',name:'Karura'},{code:'004',name:'Kangemi'},{code:'005',name:'Mountain View'}] },
    { code:'002', name:'Dagoretti North', wards:[{code:'001',name:'Kilimani'},{code:'002',name:'Kawangware'},{code:'003',name:'Gatina'},{code:'004',name:'Kileleshwa'},{code:'005',name:'Kabiro'}] },
    { code:'003', name:'Dagoretti South', wards:[{code:'001',name:'Mutu-ini'},{code:'002',name:'Ngando'},{code:'003',name:'Riruta'},{code:'004',name:'Uthiru/Ruthimitu'},{code:'005',name:'Waithaka'}] },
    { code:'004', name:'Langata', wards:[{code:'001',name:'Karen'},{code:'002',name:'Nairobi West'},{code:'003',name:'Mugumo-ini'},{code:'004',name:'South C'},{code:'005',name:'Nyayo Highrise'}] },
    { code:'005', name:'Kibra', wards:[{code:'001',name:'Laini Saba'},{code:'002',name:'Lindi'},{code:'003',name:'Makina'},{code:'004',name:'Woodley/Kenyatta Golf Course'},{code:'005',name:'Sarangombe'}] },
    { code:'006', name:'Roysambu', wards:[{code:'001',name:'Githurai'},{code:'002',name:'Kahawa West'},{code:'003',name:'Zimmerman'},{code:'004',name:'Roysambu'},{code:'005',name:'Kahawa'}] },
    { code:'007', name:'Kasarani', wards:[{code:'001',name:'Clay City'},{code:'002',name:'Mwiki'},{code:'003',name:'Kasarani'},{code:'004',name:'Njiru'},{code:'005',name:'Ruai'}] },
    { code:'008', name:'Ruaraka', wards:[{code:'001',name:'Baba Dogo'},{code:'002',name:'Utalii'},{code:'003',name:'Mathare North'},{code:'004',name:'Lucky Summer'},{code:'005',name:'Korogocho'}] },
    { code:'009', name:'Embakasi South', wards:[{code:'001',name:'Imara Daima'},{code:'002',name:'Kwa Njenga'},{code:'003',name:'Kwa Reuben'},{code:'004',name:'Pipeline'},{code:'005',name:'Kware'}] },
    { code:'010', name:'Embakasi North', wards:[{code:'001',name:'Kariobangi North'},{code:'002',name:'Dandora Area I'},{code:'003',name:'Dandora Area II'},{code:'004',name:'Dandora Area III'},{code:'005',name:'Dandora Area IV'}] },
    { code:'011', name:'Embakasi Central', wards:[{code:'001',name:'Kayole North'},{code:'002',name:'Kayole South'},{code:'003',name:'Kayole Central'},{code:'004',name:'Komarock'},{code:'005',name:'Matopeni/Spring Valley'}] },
    { code:'012', name:'Embakasi East', wards:[{code:'001',name:'Upper Savanna'},{code:'002',name:'Lower Savanna'},{code:'003',name:'Embakasi'},{code:'004',name:'Utawala'},{code:'005',name:'Mihango'}] },
    { code:'013', name:'Embakasi West', wards:[{code:'001',name:'Umoja I'},{code:'002',name:'Umoja II'},{code:'003',name:'Mowlem'},{code:'004',name:'Kariobangi South'}] },
    { code:'014', name:'Makadara', wards:[{code:'001',name:'Maringo/Hamza'},{code:'002',name:'Viwandani'},{code:'003',name:'Harambee'},{code:'004',name:'Makongeni'}] },
    { code:'015', name:'Kamukunji', wards:[{code:'001',name:'Pumwani'},{code:'002',name:'Eastleigh North'},{code:'003',name:'Eastleigh South'},{code:'004',name:'Airbase'},{code:'005',name:'California'}] },
    { code:'016', name:'Starehe', wards:[{code:'001',name:'Nairobi Central'},{code:'002',name:'Ngara'},{code:'003',name:'Pangani'},{code:'004',name:'Ziwani/Kariokor'},{code:'005',name:'Landimawe'},{code:'006',name:'Nairobi South'}] },
    { code:'017', name:'Mathare', wards:[{code:'001',name:'Hospital'},{code:'002',name:'Mabatini'},{code:'003',name:'Huruma'},{code:'004',name:'Ngei'},{code:'005',name:'Mlango Kubwa'},{code:'006',name:'Kiamaiko'}] },
  ]},
];

export default KENYA_LOCATIONS;
